[package]
name = "cargo-ui"
version = "0.3.1"
authors = ["Slint Developers <info@slint-ui.com>"]
edition = "2021"
build = "build.rs"
license = "GPL-3.0-only"
description = "GUI for cargo"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "ui", "gui"]
repository = "https://github.com/slint-ui/cargo-ui"
resolver = "2"

[features]
slint-backend-qt = ["slint/backend-qt"]
slint-backend-gl-all = ["slint/backend-gl-all"]
slint-backend-gl-wayland = ["slint/backend-gl-wayland"]
slint-backend-gl-x11 = ["slint/backend-gl-x11"]

default = ["slint-backend-qt", "slint-backend-gl-all"]

[dependencies]
anyhow = "1.0.53"
cargo_metadata = "0.14"
crates-index = { version = "0.18.0" }
dunce = "1.0.2"
futures = "0.3"
itertools = "0.10"
open = "2.0.2"
rfd = { version = "0.8.2", default-features = false, features = [ "xdg-portal" ] }
serde = "1.0.136"
serde_json = "1.0.78"
shlex = "1.1"
slint = { version = "0.2.4", default-features = false, features = [ "compat-0-2-0" ] }
tokio = { version = "1.16.1", features= ["full"] }
toml_edit = "0.14.3"
git2 = "0.14.3"

[build-dependencies]
slint-build = { version = "0.2.4" }
