name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Linux Dependencies
      run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v3
      with:
        path: ~/work/cargo-ui/Qt
        key: ${{ runner.os }}-${{ github.job }}-Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
      with:
        key: rust_cache

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: stable
            components: rustfmt
      - name: Run rustfmt
        run: cargo fmt --all -- --check
